apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eutlas

resources:
  - ../base
  - cluster-role-binding.yaml

patches:
  - path: ingress-patch.yaml
  - path: backend-mongodb-ha-ca-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: eutlas-backend
  - patch: |-
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    target:
      kind: Deployment
      name: eutlas-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: eutlas-frontend
  - patch: |-
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    target:
      kind: Deployment
      name: eutlas-frontend

configMapGenerator:
  - name: eutlas-env
    literals:
      - ENVIRONMENT=production

images:
  - name: ghcr.io/stschuer/eutlas-backend
    newTag: latest
  - name: ghcr.io/stschuer/eutlas-frontend
    newTag: latest

